# title: Ubeiden Samboni
# logo: imag/avatar.png
# #description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
---
title: Ubeiden Samboni
logo: imag/avatar.png
show_downloads: true
theme: jekyll-theme-minimal
---

# Ubeiden Samboni

![My Avatar](imag/avatar.png)

[Download my CV (PDF)](https://github.com/ubeidensamboni/curriculum-vitae/blob/main/pdf/FullCV_Ubeiden.pdf)

<!-- Social Media Links -->
<div>
    <a href="https://github.com/ubeidensamboni" target="_blank">
        <i class="fab fa-github fa-2x"></i>
    </a>
    <a href="https://www.linkedin.com/in/samboni-0812b1196/" target="_blank">
        <i class="fab fa-linkedin fa-2x"></i>
    </a>
</div>
