# title: Ubeiden Samboni
# logo: imag/avatar.png
# #description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
---
title: Ubeiden Samboni
logo: imag/avatar.png
show_downloads: true
theme: jekyll-theme-minimal
---

# Ubeiden Samboni

![My Avatar](imag/avatar.png)

[Download my CV (PDF)](link_to_your_cv.pdf)

<!-- Social Media Links -->
<div>
    <a href="https://github.com/your-github-username" target="_blank">
        <i class="fab fa-github fa-2x"></i>
    </a>
    <a href="https://www.linkedin.com/in/your-linkedin-username/" target="_blank">
        <i class="fab fa-linkedin fa-2x"></i>
    </a>
</div>
